version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: temp123321

  app:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      - PORT=80
      - APP_ENV=test
